### ISSUE TITLE
HTTP protocol binding trait deserializers

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#10]
https://awslabs.github.io/smithy/spec/http.html#httpheader-trait
- [ ] code on http trait 
- [ ] httpError (and optional code)
- [ ] httpHeader—some complexity, may support lists of timestamps requiring complex parsing
- [ ] httpPayload
- [ ] httpPrefix headers
