### ISSUE TITLE
S3 Customizations

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#144]
There is a lot here. These all need to be scoped and designed
- [ ] SSE customer key: https://github.com/awslabs/smithy-rs/issues/126
- [x] Parsing ARNs from input parameters
- [x] Custom endpoint based on input, configuration, and region.
- [x] Accelerate, dualstack, seaport, accesspoints,
- [x] Trailing checksums https://github.com/awslabs/smithy-rs/issues/1263
- [ ] ~Change GetBucketLocation’s response LocationConstraint to match AWS region names. *(Probably should be removed)?*~
- [x] Fix GetBucketLocation to be unwrapped during operation deserialization (aws-sdk-rust#116)
- [x] Additional request ID header: HostID https://github.com/awslabs/smithy-rs/issues/422
- [x] BucketName to endpoint (virtual host addressing)
- [ ] ~Auto decodes gzip response~

**Comment by jdisanti** [comment]
I think most of these will be solved by endpoints 2.0. Adding the `retriage` tag to confirm and update the issue later.

**Comment by jdisanti** [comment]
Only SSE customer key will remain after endpoints 2.0.

**Comment by jdisanti** [comment]
SSE tracked in https://github.com/smithy-lang/smithy-rs/issues/126
