### ISSUE TITLE
IO Stack V0

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#154]
MVP of traits / IO stack, probably with Hyper. Draft: #152 
- [x] Add operation to smithy_http (#169)
- [x] Add `middleware-tracing`
- [x] Finalize credential providers (#149, #148)
- [x] Endpoint design (#165)
- [x] AWS-hyper client implementation
- [x] Retries (#164, #163)
