### ISSUE TITLE
Improve and stabilize `aws-sigv4`

### ISSUE THREAD

**Issue by jdisanti** [smithy-lang/smithy-rs#1792]
- [ ] Make the API more user-friendly and ergonomic
- [ ] Add documentation and examples
  - [ ] How to sign a request
  - [ ] How to verify a request
  - [ ] How to sign a request that's going to API Gateway

**Comment by OGoodness** [comment]
+1

**Comment by aajtodd** [comment]
`aws-sigv4` crate is stable/GA, closing this
