### ISSUE TITLE
Tracking: Runtime crate `ConfigBag` semver issues

### ISSUE THREAD

**Issue by jdisanti** [smithy-lang/smithy-rs#3319]
- [x] https://github.com/smithy-lang/smithy-rs/pull/3325
- [x] https://github.com/smithy-lang/smithy-rs/pull/3318
- [x] Minimal independent crate versioning for runtime crates
    - [x] CI tool to verify runtime versioning done correctly in each PR / during release (https://github.com/smithy-lang/smithy-rs/pull/3332)
    - [x] Update smithy-rs release process (https://github.com/smithy-lang/smithy-rs/pull/3351)
- [ ] Fix event stream deferred signer sender
    - [ ] 1.x aws-smithy-eventstream
    - [ ] 0.60.x semver trick
- [x] Verify fixes
- [x] #3368

**Comment by jdisanti** [comment]
Deferred the event stream fixes to https://github.com/smithy-lang/smithy-rs/issues/3370
